import { useState } from "react";
import { ArrowUpRight, Check, ChevronDown, Menu, MoveRight, Sparkles, Star, X } from "lucide-react";

const skills = ["Digital Marketing", "Social Media Strategy", "Content Creation", "Campaign Management", "Project Management", "Communication"];
const experience = [
  { year: "PRESENT", role: "NSS Coordinator", org: "SNS College of Technology", body: "Coordinating social service and awareness programs, managing student volunteers, organizing community outreach, and building leadership through action." },
  { year: "TEXPERIA-26", role: "Workshop Organizer", org: "SNS College of Technology", body: "Successfully organized and conducted the Texperia workshop, coordinating participants, technical sessions, event logistics, and team activities." },
];

export default function Home() {
  const [menuOpen, setMenuOpen] = useState(false);
  const [activeFaq, setActiveFaq] = useState<number | null>(0);
  const [copied, setCopied] = useState(false);
  const copyToken = () => { navigator.clipboard?.writeText("suryavijay0107@gmail.com"); setCopied(true); window.setTimeout(() => setCopied(false), 1800); };
  return <main className="site-shell">
    <div className="announcement"><span className="announcement-dot" /> Electrical & Electronics Engineering student <a href="#about">View profile <ArrowUpRight size={14} /></a></div>
    <nav className="nav container" aria-label="Main navigation"><a className="wordmark" href="#top" aria-label="Surya Vijayakumar home"><span className="mark"><i /><i /><i /></span>surya<span className="wordmark-dot">.</span></a><div className={`nav-links ${menuOpen ? "is-open" : ""}`}><a href="#about" onClick={() => setMenuOpen(false)}>About</a><a href="#experience" onClick={() => setMenuOpen(false)}>Experience</a><a href="#skills" onClick={() => setMenuOpen(false)}>Skills</a><a href="#education" onClick={() => setMenuOpen(false)}>Education</a><a className="nav-cta" href="mailto:suryavijay0107@gmail.com" onClick={() => setMenuOpen(false)}>Let's connect <MoveRight size={16} /></a></div><button className="menu-toggle" aria-label={menuOpen ? "Close menu" : "Open menu"} onClick={() => setMenuOpen(!menuOpen)}>{menuOpen ? <X /> : <Menu />}</button></nav>

    <section className="hero container" id="top"><div className="hero-copy"><div className="eyebrow"><span className="eyebrow-star">✳</span> Rotaract Surya / portfolio 2025</div><h1>Build with<br /><em>purpose.</em></h1><p className="hero-lede">I’m Surya Vijayakumar, an Electrical and Electronics Engineering student who brings people, ideas, and meaningful projects together.</p><div className="hero-actions"><a className="button button-primary" href="#experience">Explore my work <ArrowUpRight size={17} /></a><a className="text-link" href="mailto:suryavijay0107@gmail.com">Get in touch <MoveRight size={17} /></a></div><div className="hero-proof"><div className="avatar-stack"><span>SV</span><span>NSS</span><span>R</span><span className="avatar-more">+</span></div><span>Leadership, communication & teamwork<br /><strong>Always learning. Always contributing.</strong></span></div></div><div className="hero-art profile-art" aria-label="Portrait of Surya Vijayakumar"><div className="art-grid" /><div className="art-sun" /><div className="art-blob" /><div className="art-ring" /><div className="art-spark spark-one">✦</div><div className="art-spark spark-two">✳</div><div className="art-label label-one">curious mind</div><div className="art-label label-two">good energy</div><div className="portrait-frame"><img src="/assets/resume-asset-000.png" alt="Surya Vijayakumar" /><span className="portrait-tag">SURYA / 01</span></div></div></section>

    <div className="ticker"><div className="ticker-track"><span>LEAD WITH PURPOSE</span><b>✳</b><span>CREATE WITH CARE</span><b>✦</b><span>KEEP LEARNING</span><b>●</b><span>LEAD WITH PURPOSE</span><b>✳</b><span>CREATE WITH CARE</span></div></div>

    <section className="section container" id="about"><div className="section-heading"><div><span className="kicker">01 / ABOUT ME</span><h2>Technical mind.<br /><em>Human heart.</em></h2></div><p>Motivated and enthusiastic about organizing events, social service activities, and technical workshops—and using every experience to grow.</p></div><div className="feature-grid"><article className="feature-card lilac"><div className="feature-top"><span className="feature-number">01</span><span className="feature-icon"><Sparkles size={21} /></span></div><h3>Leadership that moves people</h3><p>Experienced in coordinating student activities through NSS and Rotaract.</p><a href="#experience" className="round-arrow" aria-label="View leadership experience"><ArrowUpRight size={18} /></a></article><article className="feature-card butter"><div className="feature-top"><span className="feature-number">02</span><span className="feature-icon"><Star size={21} /></span></div><h3>Communication that connects</h3><p>Confident public speaker and collaborator who turns team energy into shared outcomes.</p><a href="#skills" className="round-arrow" aria-label="View skills"><ArrowUpRight size={18} /></a></article><article className="feature-card mint"><div className="feature-top"><span className="feature-number">03</span><span className="feature-icon"><span>8.23</span></span></div><h3>Learning with intention</h3><p>Currently pursuing B.E. Electrical and Electronics Engineering at SNS College of Technology.</p><a href="#education" className="round-arrow" aria-label="View education"><ArrowUpRight size={18} /></a></article></div></section>

    <section className="principles-section" id="experience"><div className="container principles-wrap"><div className="principles-copy"><span className="kicker">02 / EXPERIENCE</span><h2>Make an<br />impact that <em>lasts.</em></h2><p>From community outreach to technical workshops, I enjoy creating structured experiences that help people participate, learn, and belong.</p><a className="button button-dark" href="mailto:suryavijay0107@gmail.com">Work with me <MoveRight size={17} /></a></div><div className="experience-list">{experience.map(item => <article className="experience-item" key={item.role}><span className="experience-year">{item.year}</span><h3>{item.role}</h3><strong>{item.org}</strong><p>{item.body}</p></article>)}</div></div></section>

    <section className="section components-section container" id="skills"><div className="section-heading compact"><div><span className="kicker">03 / EXPERTISE</span><h2>Skills for<br /><em>real momentum.</em></h2></div><button className="token-chip" onClick={copyToken}>{copied ? <><Check size={15} /> Email copied!</> : <><span className="token-dot" /> suryavijay0107@gmail.com</>}</button></div><div className="skill-board">{skills.map((skill, index) => <div className={`skill-pill skill-${index % 4}`} key={skill}><span>0{index + 1}</span>{skill}</div>)}</div></section>

    <section className="faq-section" id="education"><div className="container faq-layout"><div><span className="kicker">04 / ACADEMIC DATA</span><h2>Learning is<br /><em>the long game.</em></h2><p>Building a strong technical foundation while staying active in leadership, service, and student engagement.</p><div className="education-stat"><strong>8.23</strong><span>Current CGPA<br />B.E. Electrical & Electronics Engineering</span></div></div><div className="education-list"><div className="education-item"><span>2025 — PRESENT</span><h3>SNS College of Technology</h3><p>B.E. Electrical and Electronics Engineering</p></div><div className="education-item"><span>2024 — 2025</span><h3>Higher Secondary Education</h3><p>HSC completed</p></div><div className="education-item"><span>2022 — 2023</span><h3>Secondary School Education</h3><p>SSLC completed</p></div></div></div></section>

    <section className="cta-section container" id="contact"><div className="cta-shape shape-left" /><div className="cta-shape shape-right" /><span className="eyebrow"><span className="eyebrow-star">✳</span> Open to meaningful opportunities</span><h2>Let’s build something<br /><em>worth remembering.</em></h2><p>Reach out for collaborations, projects, workshops, and good conversations.</p><a className="button button-dark" href="mailto:suryavijay0107@gmail.com">suryavijay0107@gmail.com <ArrowUpRight size={17} /></a></section>

    <footer className="footer container"><a className="wordmark" href="#top"><span className="mark"><i /><i /><i /></span>surya<span className="wordmark-dot">.</span></a><span>© 2025 Surya Vijayakumar · Coimbatore</span><div><a href="#experience">Experience</a><a href="#education">Education</a><a href="tel:+919003854520">Call</a></div></footer>
  </main>;
}
